version: 2
updates:
  - package-ecosystem: nuget
    directory: "/"
    schedule:
      interval: monthly
    open-pull-requests-limit: 5
    groups:
      dotnet-minor:
        update-types:
          - minor
          - patch
    commit-message:
      prefix: "deps"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
    open-pull-requests-limit: 5
    groups:
      all-actions:
        patterns:
          - "*"
    commit-message:
      prefix: "ci"
