// <auto-generated />
using System;
using Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entity.Enrollment", b =>
                {
                    b.Property<int>("StudentID")
                        .HasColumnType("int");

                    b.Property<int>("SubjectID")
                        .HasColumnType("int");

                    b.Property<int>("SchoolYearID")
                        .HasColumnType("int");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.HasKey("StudentID", "SubjectID", "SchoolYearID");

                    b.HasIndex("SchoolYearID");

                    b.HasIndex("SubjectID");

                    b.ToTable("Enrollment", null, t =>
                        {
                            t.HasCheckConstraint("CK_Enrollment_Status", "[Status] BETWEEN 1 AND 3");
                        });
                });

            modelBuilder.Entity("Domain.Entity.Exam", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<byte?>("Grade")
                        .HasColumnType("tinyint");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("SignedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("StudentID")
                        .HasColumnType("int");

                    b.Property<int>("SubjectID")
                        .HasColumnType("int");

                    b.Property<int>("TeacherID")
                        .HasColumnType("int");

                    b.Property<int>("TermID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("TeacherID");

                    b.HasIndex("StudentID", "SubjectID", "TermID")
                        .IsUnique();

                    b.ToTable("Exam", null, t =>
                        {
                            t.HasCheckConstraint("CK_Exam_Grade", "[Grade] BETWEEN 5 AND 10");
                        });
                });

            modelBuilder.Entity("Domain.Entity.Person", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("JMBG")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("char(13)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.HasIndex("JMBG")
                        .IsUnique()
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("Person", null, t =>
                        {
                            t.HasCheckConstraint("CK_Person_DateOfBirth_Range", "[DateOfBirth] >= '1900-01-01' AND [DateOfBirth] <= CONVERT(date, GETDATE())");

                            t.HasCheckConstraint("CK_Person_JMBG_13Digits", "LEN([JMBG]) = 13 AND PATINDEX('%[^0-9]%', [JMBG]) = 0");
                        });

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Domain.Entity.Registration", b =>
                {
                    b.Property<int>("SubjectID")
                        .HasColumnType("int");

                    b.Property<int>("StudentID")
                        .HasColumnType("int");

                    b.Property<int>("TermID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("datetime2");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.HasKey("SubjectID", "StudentID", "TermID");

                    b.HasIndex("StudentID");

                    b.HasIndex("TermID");

                    b.ToTable("Registration", null, t =>
                        {
                            t.HasCheckConstraint("CK_Registration_Status", "[Status] BETWEEN 1 AND 2");
                        });
                });

            modelBuilder.Entity("Domain.Entity.SchoolYear", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("ID");

                    b.ToTable("SchoolYear", null, t =>
                        {
                            t.HasCheckConstraint("CK_SchoolYear_EndDate_After_StartDate", "[EndDate]>[StartDate]");
                        });
                });

            modelBuilder.Entity("Domain.Entity.StudentStats", b =>
                {
                    b.Property<int>("ECTSCount")
                        .HasColumnType("int");

                    b.Property<decimal>("GPA")
                        .HasColumnType("decimal(4,2)");

                    b.Property<int>("StudentID")
                        .HasColumnType("int")
                        .HasColumnName("StudentID");

                    b.ToTable((string)null);

                    b.ToView("vw_StudentStats", (string)null);
                });

            modelBuilder.Entity("Domain.Entity.Subject", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<byte>("ECTS")
                        .HasColumnType("tinyint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID");

                    b.ToTable("Subject", null, t =>
                        {
                            t.HasCheckConstraint("CK_Subject_ECTS", "[ECTS] BETWEEN 1 AND 15");
                        });
                });

            modelBuilder.Entity("Domain.Entity.TeachingAssignment", b =>
                {
                    b.Property<int>("SubjectID")
                        .HasColumnType("int");

                    b.Property<int>("TeacherID")
                        .HasColumnType("int");

                    b.Property<bool>("CanGrade")
                        .HasColumnType("bit");

                    b.HasKey("SubjectID", "TeacherID");

                    b.HasIndex("TeacherID");

                    b.ToTable("TeachingAssignment", (string)null);
                });

            modelBuilder.Entity("Domain.Entity.Term", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateOnly>("RegistrationEndDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("RegistrationStartDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("ID");

                    b.ToTable("Term", null, t =>
                        {
                            t.HasCheckConstraint("CK_Term_EndDate_After_StartDate", "[EndDate] > [StartDate]");

                            t.HasCheckConstraint("CK_Term_RegEndDate_After_RegStartDate", "[RegistrationEndDate] > [RegistrationStartDate]");
                        });
                });

            modelBuilder.Entity("Domain.Entity.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("PersonID")
                        .HasColumnType("int");

                    b.Property<byte>("Role")
                        .HasColumnType("tinyint");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("isActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("ID");

                    b.HasIndex("PersonID")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("User", null, t =>
                        {
                            t.HasCheckConstraint("CK_User_Role", "[Role] BETWEEN 1 AND 3");
                        });
                });

            modelBuilder.Entity("Domain.Entity.Student", b =>
                {
                    b.HasBaseType("Domain.Entity.Person");

                    b.Property<string>("IndexNumber")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.HasIndex("IndexNumber")
                        .IsUnique()
                        .HasFilter("[IndexNumber] IS NOT NULL");

                    b.ToTable("Student", null, t =>
                        {
                            t.HasCheckConstraint("CK_Person_DateOfBirth_Range", "[DateOfBirth] >= '1900-01-01' AND [DateOfBirth] <= CONVERT(date, GETDATE())");

                            t.HasCheckConstraint("CK_Person_JMBG_13Digits", "LEN([JMBG]) = 13 AND PATINDEX('%[^0-9]%', [JMBG]) = 0");

                            t.HasCheckConstraint("CK_Student_IndexNumber_Format", "[IndexNumber] LIKE '[0-9][0-9][0-9][0-9]/[0-9][0-9][0-9][0-9]'");
                        });
                });

            modelBuilder.Entity("Domain.Entity.Teacher", b =>
                {
                    b.HasBaseType("Domain.Entity.Person");

                    b.Property<string>("EmployeeNumber")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<byte>("Title")
                        .HasColumnType("tinyint");

                    b.HasIndex("EmployeeNumber")
                        .IsUnique()
                        .HasFilter("[EmployeeNumber] IS NOT NULL");

                    b.ToTable("Teacher", null, t =>
                        {
                            t.HasCheckConstraint("CK_Person_DateOfBirth_Range", "[DateOfBirth] >= '1900-01-01' AND [DateOfBirth] <= CONVERT(date, GETDATE())");

                            t.HasCheckConstraint("CK_Person_JMBG_13Digits", "LEN([JMBG]) = 13 AND PATINDEX('%[^0-9]%', [JMBG]) = 0");

                            t.HasCheckConstraint("CK_Teacher_EmployeeNumber_Format", "[EmployeeNumber] LIKE '[0-9][0-9][0-9][0-9]/[0-9][0-9][0-9][0-9]'");

                            t.HasCheckConstraint("CK_Teacher_Title", "[Title] BETWEEN 1 AND 4");
                        });
                });

            modelBuilder.Entity("Domain.Entity.Enrollment", b =>
                {
                    b.HasOne("Domain.Entity.SchoolYear", "SchoolYear")
                        .WithMany("Enrollments")
                        .HasForeignKey("SchoolYearID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entity.Student", "Student")
                        .WithMany("Enrollments")
                        .HasForeignKey("StudentID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entity.Subject", "Subject")
                        .WithMany("Enrollments")
                        .HasForeignKey("SubjectID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SchoolYear");

                    b.Navigation("Student");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("Domain.Entity.Exam", b =>
                {
                    b.HasOne("Domain.Entity.Teacher", "Teacher")
                        .WithMany("SignedExams")
                        .HasForeignKey("TeacherID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entity.Registration", "Registration")
                        .WithOne("Exam")
                        .HasForeignKey("Domain.Entity.Exam", "StudentID", "SubjectID", "TermID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Registration");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("Domain.Entity.Registration", b =>
                {
                    b.HasOne("Domain.Entity.Student", "Student")
                        .WithMany("Registrations")
                        .HasForeignKey("StudentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entity.Subject", "Subject")
                        .WithMany("Registrations")
                        .HasForeignKey("SubjectID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entity.Term", "Term")
                        .WithMany("Registrations")
                        .HasForeignKey("TermID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("Subject");

                    b.Navigation("Term");
                });

            modelBuilder.Entity("Domain.Entity.TeachingAssignment", b =>
                {
                    b.HasOne("Domain.Entity.Subject", "Subject")
                        .WithMany("TeachingAssignments")
                        .HasForeignKey("SubjectID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entity.Teacher", "Teacher")
                        .WithMany("TeachingAssignments")
                        .HasForeignKey("TeacherID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subject");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("Domain.Entity.User", b =>
                {
                    b.HasOne("Domain.Entity.Person", "Person")
                        .WithOne("User")
                        .HasForeignKey("Domain.Entity.User", "PersonID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Domain.Entity.Student", b =>
                {
                    b.HasOne("Domain.Entity.Person", null)
                        .WithOne()
                        .HasForeignKey("Domain.Entity.Student", "ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entity.Teacher", b =>
                {
                    b.HasOne("Domain.Entity.Person", null)
                        .WithOne()
                        .HasForeignKey("Domain.Entity.Teacher", "ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entity.Person", b =>
                {
                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entity.Registration", b =>
                {
                    b.Navigation("Exam");
                });

            modelBuilder.Entity("Domain.Entity.SchoolYear", b =>
                {
                    b.Navigation("Enrollments");
                });

            modelBuilder.Entity("Domain.Entity.Subject", b =>
                {
                    b.Navigation("Enrollments");

                    b.Navigation("Registrations");

                    b.Navigation("TeachingAssignments");
                });

            modelBuilder.Entity("Domain.Entity.Term", b =>
                {
                    b.Navigation("Registrations");
                });

            modelBuilder.Entity("Domain.Entity.Student", b =>
                {
                    b.Navigation("Enrollments");

                    b.Navigation("Registrations");
                });

            modelBuilder.Entity("Domain.Entity.Teacher", b =>
                {
                    b.Navigation("SignedExams");

                    b.Navigation("TeachingAssignments");
                });
#pragma warning restore 612, 618
        }
    }
}
